### ISSUE TITLE
Shoudn't open the sidebar when it's hidden.

### ISSUE THREAD

**Issue by dummifiedme** [shichongrui/obsidian-reveal-active-file#1]
The plugin currently opens sidebar whenever I create a file. I know it is meant to reveal the file, but can it not really do that without opening the sidebar? It creates a distraction while writing. 
Also, when using in a reduced window size it ceates a hassle to hide sidebar everytime I create or navigate a new page

**Comment by shichongrui** [comment]
I'll take a look into seeing if I can not trigger the "Reveal active file in navigator" command if the sidebar is closed.

**Comment by tonyxiao** [comment]
+1 for thius

**Comment by MavropaliasG** [comment]
+1, please @shichongrui !! It's really annoying

**Comment by Elaws** [comment]
@dummifiedme : Great suggestion, came here to suggest this. Until this gets implemented, I'll have to revert back to using native shortcut to show only when desired. I use the following shortcuts :

`Ctrl + shift + H` : Reveal active file in explorer.

(Not directly related, but these shortcuts are also quite useful :
`Ctrl + shift + J` : Hide/Reveal left sidebar.
`Ctrl + shift + M` : Hide/Reveal right sidebar.)

**Comment by anselmwang** [comment]
I have fixed this issue in this PR  https://github.com/shichongrui/obsidian-reveal-active-file/pull/9
Is anyone interested in trying it? I am happy to hear feedback and adjust the experience.

Current experience is:
- When file explorer is visible, auto reveal
- When file explorer is visible, disable auto reveal, so the sidebar will not auto popup. The reasons are two folds (as mentioned by @dummifiedme) : 1) the auto popup creates a distraction while writing. 2) when using in a reduced window size auto popup ceates a hassle to hide sidebar everytime I create or navigate a new page
- When file explorer is changed from hidden to visible, auto reveal. So the experience is still very similar to original plugin. This behavior is especially useful on Mobile. The sidebar is hidden most of the time due to limit screen width. If I don't add the last behavior, auto reveal basically always disabled.

**Comment by mikkovedru** [comment]
@anselmwang 
I tested your PR and it works great. :+1: Thank you! :1st_place_medal:

**Comment by shichongrui** [comment]
Released as version 1.0.2
